[book]
authors = ["nicknamenamenick","Zeglius"]
language = "en"
multilingual = false
src = "src"
title = "Bazzite Documentation"

[build]
use-default-preprocessors = false
create-missing = false

[preprocessor.links]
