[book]
authors = ["nicknamenamenick","Zeglius"]
language = "en"
multilingual = false
src = "src"
title = "Bazzite Documentation"

[build]
use-default-preprocessors = false
create-missing = false

[preprocessor.links]

[output.html]
git-repository-url="https://github.com/ublue-os/bazzite"
edit-url-template = "https://github.com/ublue-os/bazzite/edit/main/docs/{path}"
